name: CI
# Controles de evento para execução
on:
 # Atualização na branch “MASTER/MAIN” por push ou pull-request
 push:
  branches: [ "qa" ]
 pull_request:
  branches: [ "qa" ]
# JOBS de atividade
jobs:
 # Task com nome BUILD
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - name: Run a one-line script
     run: echo Hello, world!
   - name: Run a multi-line script
     run: |
      echo Add other actions to build,
      echo test, and deploy your project.
